import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Provider from "./StoreProvider"
import { Header } from "./components/Header/Header"
import { RecordForm } from "./components/RecordForm/RecordForm"
import { FilterLinks } from "./components/FilterLinks/FilterLinks"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Todo list",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>): React.ReactNode {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <main>
          <Provider><RecordForm/></Provider>
          <FilterLinks/>
          <Provider>{children}</Provider>
        </main>
      </body>
    </html>
  )
}