import type { Metadata } from "next"
import { Roboto, Lusitana } from "next/font/google"
import Provider from "./StoreProvider"
import { Header } from "./components/Header/Header"
import { RecordForm } from "./components/RecordForm/RecordForm"
import { FilterLinks } from "./components/FilterLinks/FilterLinks"
import "./styles/globals.css"

const roboto = Roboto({ 
  subsets: ["latin"],
  weight: ['300','400','700'],
  variable: '--roboto',
  display: 'swap'
})

const lustina = Lusitana({
  subsets: ["latin"],
  weight: ['400','700'],
  variable: '--lustina',
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Todo list",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>): React.ReactNode {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${lustina.variable}`}>
        <Header/>
        <main>
          <Provider>
            <RecordForm/>
            <FilterLinks/>
            {children}
          </Provider>
        </main>
      </body>
    </html>
  )
}